version: '3'
services:

  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    domainname: config
    ports:
      - "8888:8888"
    restart: always
    networks:
      - some-net

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - some-net

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    domainname: core
    ports:
      - "8189:8189"
    restart: always
    networks:
      - some-net
    depends_on:
      - config
      - eureka

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    restart: always
    networks:
      - some-net
    depends_on:
      - config
      - eureka

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - some-net
    depends_on:
      - config
      - eureka

  security:
    build:
      context: ./security
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    restart: always
    networks:
      - some-net
    depends_on:
      - config
      - eureka

  storage-app:
    build:
      context: ./storage-app
      dockerfile: Dockerfile
    ports:
      - "8191:8191"
    volumes:
      - ./storage:/app/storage
    restart: always
    networks:
      - some-net
    depends_on:
      - config
      - eureka

networks:
  some-net: