server:
  port: 3000
  servlet:
    context-path: /front
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka:8761/eureka
      defaultZone: http://myapp-service-8761.default.svc.cluster.local:8761/eureka