server:
  port: 5555

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core
#          uri: http://core:8189
          uri: http://myapp-service-8189.default.svc.cluster.local:8189
#          uri: lb://CORE
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
            - JwtAuthFilter
        - id: cart
#          uri: http://cart:8190
          uri: http://myapp-service-8190.default.svc.cluster.local:8190
#          uri: lb://CART
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: security
#          uri: http://security:8188
          uri: http://myapp-service-8188.default.svc.cluster.local:8188
#          uri: lb://SECURITY
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
            - PrefixPath=/security
            - JwtAuthFilter
        - id: store
#          uri: http://storage-app:8191
          uri: http://myapp-service-8191.default.svc.cluster.local:8191
#          uri: lb://STORAGE-APP
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
            - PrefixPath=/store
            - JwtAuthFilter

jwt:
  secret: secretKey

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: TRACE
    reactor.netty: TRACE