server:
  port: 8189
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka:8761/eureka
integrations:
  cart-service:
    url: http://cart:8190/cart/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  storage-app:
    url: http://gateway:5555/store/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: DEBUG
  file:
    name: /var/log/core.log